from PyQt5.QtWidgets import QPushButton, QWidget, QLabel, QRadioButton, QHBoxLayout, QVBoxLayout, QButtonGroup, QGroupBox, QSpinBox
from memo_app import app

window = QWidget()
rew = QPushButton("меню")
rew1 = QPushButton("відпочити")
rew2 = QSpinBox()
rew2.setValue(30)
rew3 = QLabel("")
rew4 = QPushButton("Відповісти")
wer4 = QGroupBox("Варіанти відповідей")
wer5 = QButtonGroup()
wer6 = QRadioButton("")
wer7 = QRadioButton("")
wer8 = QRadioButton("")
wer9 = QRadioButton("")
wer5.addButton(wer6)
wer5.addButton(wer7)
wer5.addButton(wer8)
wer5.addButton(wer9)
wer10 = QGroupBox("Результати тесту")
wer11 = QLabel("")
wer12 = QLabel("")
wer13 = QVBoxLayout()
wer14 = QVBoxLayout()
wer15 = QHBoxLayout()
wer13.addWidget(wer6)
wer13.addWidget(wer7)
wer14.addWidget(wer8)
wer14.addWidget(wer9)
wer15.addLayout(wer13)
wer15.addLayout(wer14)
wer4.setLayout(wer15)
wer16 = QVBoxLayout()
wer16.addWidget(wer11)
wer16.addWidget(wer12)
wer10.setLayout(wer16)
wer10.hide()
wer17 = QHBoxLayout()
wer18 = QHBoxLayout()
wer19 = QHBoxLayout()
wer20 = QHBoxLayout()
wer17.addWidget(rew)
wer17.addStretch(1)
wer17.addWidget(rew1)
wer17.addWidget(rew2)
wer17.addWidget(QLabel("хвилин"))
wer18.addWidget(rew3)
wer19.addWidget(wer4)
wer19.addWidget(wer10)
wer20.addStretch(1)
wer20.addWidget(rew4, stretch=2)
wer20.addStretch(1)
wer21 = QVBoxLayout()
wer21.addLayout(wer17, stretch=1)
wer21.addLayout(wer18, stretch=2)
wer21.addLayout(wer19, stretch=8)
wer21.addStretch(1)
wer21.addLayout(wer20, stretch=1)
wer21.addStretch(1)


def resultat():
    wer10.show()
    wer4.hide()
    rew4.setText("наступне питання")


def question():
    wer10.hide()
    wer4.show()
    rew4.setText("відповісти")
    wer5.setExclusive(False)
    wer6.setChecked(False)
    wer7.setChecked(False)
    wer8.setChecked(False)
    wer9.setChecked(False)
    wer5.setExclusive(True)
